project:
  type: website
  output-dir: docs
website:
  title: "STATR"
  navbar:
    left:
      - text: "A propos"
        menu:
          - text: "Objectifs du cours"
            href: index.qmd
      - text: "STATR0 : Office Killer"
        menu: 
        - text: "---- R & R STUDIO : OFFICE KILLER ----"
        - href: STAT0-Excel_Killer.qmd
          text: "Les programmes R : Excel Killer ?"
        - href: STAT0-Word_Killer.qmd
          text: "Les documents Rmd : Word Killer ?"
      - text: "STATR1 : Variables"
        menu:           
        - text: "--- STATR1: VARIABLES STATISTIQUES ----"
        - href: STAT1-Variables-Cours.html
          text: "Cours : Types de variables" 
          target: "_blank"
        - href: STAT1-Exo1.qmd
          text: "Exo1 : Premiers pas dans R"
        - href: STAT1-Exo2.qmd
          text: "Exo2 : Les femmes du Bénin"
      - text: "STATR2 : Univarié"
        menu:           
        - text: "---- STAT2 : STATISTIQUE EXPLORATOIRE----"
        - href: STAT2-Explor-Cours.html
          text: "Cours : Exploration avec R-base"
          target: "_blank"
        - href: STAT2-Exo1.qmd
          text: "Exo1 : Manipuler des tableaux"
        - href: STAT2-Exo2.qmd
          text: "Exo2 : Résumer des variables"  
      - text: "STATR3 : X et Y quanti."
        menu:           
        - text: "---- STAT3 : CORRELATION & REGRESSION ----"
        - href: STAT3-Correlation-Cours.html
          text: "Cours : Corrélation"
          target: "_blank"
        - href: STAT3-Regression-Cours.html
          text: "Cours : Régression linéaire"
          target: "_blank"
        - href: STAT3-Exo1.qmd
          text: "Exo1 : Programme-type"
      - text: "STATR4 : X et Y quali."
        menu:           
        - text: "---- STAT4 : ENQUETES & TEST DU CHI2 ----"
        - href: STAT4-Enquetes.html
          text: "Cours : Echantillonage"
          target: "_blank"
        - href: STAT4-chi2.html
          text: "Cours : Test du chi-2"
          target: "_blank"
        - href: STAT4-Exo1.qmd
          text: "Exo1 : Programme-type"
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/stats
        target: _blank
  page-footer:
    background: dark
    left: Grasland C., 2025
format:
  html:
    grid:
      sidebar-width: 100px
    theme: 
      light: minty    
      dark: solar
    css: style.scss
    toc: true


